### ISSUE TITLE
DOMNO

### ISSUE THREAD

**Issue by newprogrammer1991** [ElderJames/aspnetcore-material-universal#1]
Please help! How can we add domino?

**Comment by ElderJames** [comment]
Sorry,I don't know what you mean...

**Comment by newprogrammer1991** [comment]
I mean it https://github.com/fgnass/domino.

**Comment by newprogrammer1991** [comment]
Hi! I have tried, but doesn't work 

return renderPromise.then((response: any) => {
    console.log(response);
    const win = domino.createWindow(response.html);
    response.globals.window = win;
    return ({
      html: response.html,
      globals: response.globals
    });
  });

**Comment by ElderJames** [comment]
Thanks for your work.
But this project is aimed at angular univresal.
You may need to open the issue in universal repo.
